{% set name = "typst-test" %}
{% set version = "0.0.0.post104.7babfc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tingerrr/{{ name }}/archive/{{ version.split(".")[-1] }}.tar.gz
  sha256: a62ecf42d02cd14f3be293f9a31cddce66c48e0ee2e216c1b552d14300facc7e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typst-test --help

about:
  home: https://github.com/tingerrr/typst-test
  summary: 'A visual regression test runner for typst packages. '
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
