{% set name = "typst-test" %}
{% set version = "0.0.0.post105+699b871" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tingerrr/{{ name }}/archive/{{ version.split("+")[-1] }}.tar.gz
  sha256: e24b7e8a9684736bc85f7cd37a0aaa7f5ce571df2a0847fc2a1defc08fddfd1e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typst-test --help

about:
  home: https://github.com/tingerrr/typst-test
  summary: 'A visual regression test runner for typst packages. '
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
