{% set name = "typst-test" %}
{% set version = "0.0.0.post106+2b4e689" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tingerrr/{{ name }}/archive/{{ version.split("+")[-1] }}.tar.gz
  sha256: 099c04b3cf2bed818520b488ac9087931f7973c2e29d842052f66b296ba9e8f1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - typst-test --help

about:
  home: https://github.com/tingerrr/typst-test
  summary: 'A visual regression test runner for typst packages. '
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
